#!/bin/sh
# exec is used to 'morph' the shell interpreter process into jackd process, saving some system resources.
exec /usr/bin/jackd -t 2000 -R -P 75 -d alsa -d hw:pisound -r 48000 -p 128 -n 2 -X seq -s -S
